version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    versioning-strategy: "increase"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "towncrier"
        dependency-type: "direct"
