name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
      - '!*dev*'
      - '!*pre*'
      - '!*post*'
  pull_request:
  workflow_dispatch:
  schedule:
    #         ┌───────── minute (0 - 59)
    #         │ ┌───────── hour (0 - 23)
    #         │ │ ┌───────── day of the month (1 - 31)
    #         │ │ │ ┌───────── month (1 - 12 or JAN-DEC)
    #         │ │ │ │ ┌───────── day of the week (0 - 6 or SUN-SAT)
    - cron: '18 7 1 * *'  # Every 1st of the month at 07:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: codestyle
        - linux: build_docs
        - linux: build_docs_devtowncrier
        - linux: build_docs_incremental

  notify:
    if: always() && (github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: Cadair/matrix-notify-action@main
        with:
          matrix_token: ${{ secrets.matrix_access_token }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          homeserver: ${{ secrets.matrix_homeserver }}
          roomid: '!fZOLFXlQvSoKfLAVrd:openastronomy.org'
          ignore_pattern: '.*Load.*'
          summarise_success: false
          workflow_description: "on sphinx-changelog"

  publish:
    needs: [tests]
    if: github.event_name != 'pull_request'
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    with:
      upload_to_pypi: ${{ startsWith(github.event.ref, 'refs/tags/v') && !endsWith(github.event.ref, '.dev') }}
    secrets:
      pypi_token: ${{ secrets.PYPI_API_TOKEN }}
